return {
  -- {
  --   'yetone/avante.nvim',
  --   event = 'VeryLazy',
  --   lazy = false,
  --   version = false,
  --   opts = {
  --     provider = 'openrouter',
  --     vendors = {
  --       openrouter = {
  --         endpoint = 'https://openrouter.ai/api/v1',
  --         model = 'google/gemini-exp-1206:free',
  --         __inherited_from = 'openai',
  --         api_key_name = 'OPENROUTER_API_KEY_AVANTE',
  --       },
  --     },
  --   },
  --   build = 'make',
  --   dependencies = {
  --     'stevearc/dressing.nvim',
  --     'nvim-lua/plenary.nvim',
  --     'MunifTanjim/nui.nvim',
  --     'hrsh7th/nvim-cmp',
  --     'nvim-tree/nvim-web-devicons',
  --     'zbirenbaum/copilot.lua',
  --     {
  --       'HakonHarnes/img-clip.nvim',
  --       event = 'VeryLazy',
  --       opts = {
  --         default = {
  --           embed_image_as_base64 = false,
  --           prompt_for_file_name = false,
  --           drag_and_drop = {
  --             insert_mode = true,
  --           },
  --           use_absolute_path = true,
  --         },
  --       },
  --     },
  --     {
  --       'MeanderingProgrammer/render-markdown.nvim',
  --       opts = {
  --         file_types = { 'markdown', 'Avante' },
  --       },
  --       ft = { 'markdown', 'Avante' },
  --     },
  --   },
  -- },
}
